# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CitiesCity',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cities_city',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CitiesCountry',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('code3', models.CharField(max_length=3, unique=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('currency_name', models.CharField(blank=True, max_length=50, null=True)),
                ('language_codes', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('tld', models.CharField(max_length=5)),
                ('capital', models.CharField(max_length=100)),
                ('continent', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cities_country',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fathers',
            fields=[
                ('id', models.BigIntegerField(default=1, primary_key=True, serialize=False)),
                ('last', models.TextField(blank=True, null=True)),
                ('first', models.TextField(blank=True, null=True)),
                ('middle', models.TextField(blank=True, null=True)),
                ('city_of_birth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CitiesCity')),
                ('country_of_birth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CitiesCountry')),
            ],
            options={
                'verbose_name': 'Father',
                'db_table': 'fathers',
                'managed': True,
                'verbose_name_plural': 'Fathers',
            },
        ),
        migrations.CreateModel(
            name='Mothers',
            fields=[
                ('id', models.BigIntegerField(default=1, primary_key=True, serialize=False)),
                ('maiden', models.TextField(blank=True, null=True)),
                ('first', models.TextField(blank=True, null=True)),
                ('middle', models.TextField(blank=True, null=True)),
                ('city_of_birth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CitiesCity')),
                ('country_of_birth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CitiesCountry')),
            ],
            options={
                'verbose_name': 'Mother',
                'db_table': 'mothers',
                'managed': True,
                'verbose_name_plural': 'Mothers',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigIntegerField(default=1, primary_key=True, serialize=False)),
                ('family', models.TextField(blank=True, null=True)),
                ('first', models.TextField(blank=True, null=True)),
                ('middle', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('birth_father', models.ForeignKey(blank=True, db_column='fathers', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Fathers')),
                ('birth_mother', models.ForeignKey(blank=True, db_column='mothers', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Mothers')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curcity', to='app.CitiesCity')),
                ('city_of_birth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_of_birth', to='app.CitiesCity')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curcountry', to='app.CitiesCountry')),
                ('country_of_birth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_of_birth', to='app.CitiesCountry')),
            ],
            options={
                'verbose_name': 'Person',
                'db_table': 'person',
                'managed': True,
                'verbose_name_plural': 'People',
            },
        ),
        migrations.AddField(
            model_name='citiescity',
            name='country_code',
            field=models.ForeignKey(blank=True, db_column='code', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CitiesCountry'),
        ),
        migrations.AlterUniqueTogether(
            name='citiescity',
            unique_together=set([('country_code', 'name')]),
        ),
    ]
