# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170210_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='place_to_stay',
            field=models.NullBooleanField(),
        ),
    ]
