# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_person_place_to_stay'),
    ]

    operations = [
        migrations.AddField(
            model_name='fathers',
            name='year_born',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mothers',
            name='year_born',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='year_born',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fathers',
            name='city_of_birth',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mothers',
            name='city_of_birth',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='city_of_birth',
            field=models.TextField(blank=True, null=True),
        ),
    ]
